const tokens = {
    STUDENT_TOKEN:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODYyYjZmMC1kMTU1LTRmMTEtOGE2My1hYjM2OWI2MDZjNzQiLCJuaWNrbmFtZSI6IlJPTEVfU1RVREVOVCIsImVtYWlsIjoicm9sZV9zdHVkZW50QGV4YW1wbGUuY29tIiwicm9sZSI6IlJPTEVfU1RVREVOVCIsImlhdCI6MTc3Nzc0NTEwMCwiZXhwIjoxNzc4MzQ5OTAwfQ.SpYa_8gRfbld48xbynhhouaDC2yytbe-1NSUo0k8e1c",
    TEACHER_TOKEN:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODYyYjZmMC1kMTU1LTRmMTEtOGE2My1hYjM2OWI2MDZjNzQiLCJuaWNrbmFtZSI6IlJPTEVfVEVBQ0hFUiIsImVtYWlsIjoicm9sZV90ZWFjaGVyQGV4YW1wbGUuY29tIiwicm9sZSI6IlJPTEVfVEVBQ0hFUiIsImlhdCI6MTc3Nzc0NTEwMCwiZXhwIjoxNzc4MzQ5OTAwfQ.u_ZYHh9qvMPX2m_eS8Q30KPknNynwtVewfEYzULD1SY",
    ADMIN_TOKEN:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODYyYjZmMC1kMTU1LTRmMTEtOGE2My1hYjM2OWI2MDZjNzQiLCJuaWNrbmFtZSI6IlJPTEVfQURNSU4iLCJlbWFpbCI6InJvbGVfYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTc3Nzc0NTEwMCwiZXhwIjoxNzc4MzQ5OTAwfQ.G_i5vy38LuhDNGcqsuwUjLEydmkQh68CQYoJunXc8iQ",
};

export class IamController {
    public static async login(accessToken: string) {
        return { jwt: tokens.STUDENT_TOKEN };
    }
}
